### ISSUE TITLE
remove environment variable support

### ISSUE THREAD

**Issue by noahdietz** [30x/kiln#73]
General sentiment is (at least it was, the last time we discussed it) that having build-time env vars that ultimately get baked into the Docker image is not necessary. Thus, we should remove the option to supply them. Going to open a PR...

Thoughts? Objections? @whitlockjc  @mpnally @AdamMagaluk @jbowen93

**Comment by whitlockjc** [comment]
I thought we _liked_ the idea of baking environment variables into the image as a way to do sane defaults, or environment agnostic configuration.

**Comment by noahdietz** [comment]
Oh right, sane defaults....i forgot about that discussion...Yes, that was a compelling reason to keep them
