### ISSUE TITLE
remove ptsUrl functionality

### ISSUE THREAD

**Issue by noahdietz** [30x/kiln#76]

**Comment by noahdietz** [comment]
@whitlockjc There is a decent amount of code related to the POST & GET of podspecs with S3 or a local file storage. It is unrelated to PTS URL functionality (other than they manipulate podspecs), and I think it can be useful in the future. I would like to keep it in `kiln` as of right now. 

To remove these APIs might be a breaking change for the Oscar use-case, because this use-case has a special PTS being consumed (rather than the one generated by kiln).  But this is easily overcome I'm sure.

Lets talk about it.

**Comment by whitlockjc** [comment]
I'd rather remove anything we're not using because we can always resurrect it via Git.  As for Oscar's case, I think we need to figure out a better way to support his case.  Let's talk about it offline.

**Comment by mpnally** [comment]
Can we see Oscar's PTS?

Martin

**Comment by noahdietz** [comment]
I will remove all of the podspec functionality. 

@mpnally I don't have a way to access it on hand, we will have to talk to Jordan or Oscar to look at that pipeline they use to deploy his app. I will make a note to get a copy of it.
